### PR TITLE
Fix "ReferenceError: all_player_cards is not defined" in prosperity/forge.js

### PR DESCRIPTION
**Pull request by stasm**
I ran into

```
Exception in callback of async function: ReferenceError: all_player_cards is not defined
    at app/cards/prosperity/forge.js:33:64
```

while playing with friends.  I _think_ this should fix it.  However, do you have any recommendations for testing?  Is there a way to choose specific cards before starting a new game?

### CODE REVIEW

**Comment by jcbantuelle** [comment]
Good catch, sorry for all the bugs you're hitting. You jumped on board right when I've been in the middle of a massive refactor I haven't had a chance to play test very much. This fix would actually introduce a much more subtle potential bug, where it would be possible for cards other players have in play to improperly not affect game state.

I've got ahead and pushed a more comprehensive fix with 981ea389e42f3c43142b338a3ec4e1245b22ce3f that should address the problem more permanently. The reason it was lingering in the first place is a legacy issue where I used to back the game state with MongoDB. The performance was horrible, so I was trying to do everything I could to reduce the number of queries, hence preloading the set of all cards.

I've since dropped the MongoDB storage for game state and keep it all in memory, so it makes sense to just purge the remaining uses of `all_player_cards`. The performance cost of grabbing out of a dictionary object should be minimal.

Regarding how I test, I just pushed up a new `testing` branch you can check out that should give you what you need, 5c69872fa2a65024e2aa070487f252378b8a85f5. Basically, edit the arrays in the `test_events` and `test` functions with whatever you want your game to have. I also snapshot the game between each turn so that editing the code restores you to the beginning of the most recent turn after the server restarts, to facilitate testing fixes post server crash.

There two things to watch out for that I haven't taken the time to address yet. The first is that if you're mid-proposal when the server crashes, it can get "stuck". You can clear that in the Mongo shell with `db.proposals.remove({})`. The other is that if you have a bug in the first turn of the game, restoring the snapshot is going to bug out. You'll want to clear that with `db.users.update({}, {$unset: {current_game: ''}}, {multi: true})`.

Just let me know if you have any other questions and feel free to open issues if you run into any other bugs you're not sure how to address!

**Comment by jcbantuelle** [comment]
If you're looking for a more stable experience, you may want to roll back to b8b75582ff9f809bd19c1c30a7aaca8daa502e45. I love that the game is getting play tested, but I feel bad that you're hitting all these issues since I'm in the middle of implementing the new Empires set.

**Comment by stasm** [comment]
Thanks for fixing this!

> Good catch, sorry for all the bugs you're hitting. You jumped on board right when I've been in the middle of a massive refactor I haven't had a chance to play test very much.

I definitely didn't mean to put more pressure on you :) I'm very interested in this project and also very impressed by it so far! It might not seem like it because we're interacting through PRs which are about bugs, but you should know that we've already logged close to 100 games since Wednesday (1v1 and 1v1v1) and #9 and #10 were the only issues we ran into game-logic-wise.

> I've since dropped the MongoDB storage for game state and keep it all in memory, so it makes sense to just purge the remaining uses of all_player_cards. The performance cost of grabbing out of a dictionary object should be minimal.

So any currently played games won't persist across server restarts, but that's rather okay, right?

> Regarding how I test, I just pushed up a new testing branch you can check out that should give you what you need, 5c69872. Basically, edit the arrays in the test_events and test functions with whatever you want your game to have. I also snapshot the game between each turn so that editing the code restores you to the beginning of the most recent turn after the server restarts, to facilitate testing fixes post server crash.

Cool, thanks for the instructions!  Let me know if there's anything I can help test.  I'm also pretty familiar with Meteor.

> If you're looking for a more stable experience, you may want to roll back to b8b7558. I love that the game is getting play tested, but I feel bad that you're hitting all these issues since I'm in the middle of implementing the new Empires set.

Nah :)  I've been excluding the Empires set for now.  As soon as you feel it's ready to be play tested, I'll be happy to help!

**Comment by jcbantuelle** [comment]
That's fantastic, I'm really glad you're having so much fun with the app. You're certainly not putting any pressure on me, I love working on this project and it's even more exciting to know others are getting mileage out of it. I greatly appreciate your PRs and play testing.

You're right about games that are currently being played not persisting across server restarts. I do log the results of games in Mongo though, so historic data should persist.

Regarding Empires, feel free to dive into it whenever you want. The only thing left for me to add is the Landmark cards. I've tested each of the cards and events in isolation and they seem to work, but there's probably some edge cases I haven't thought of.

**Pull request closed without merging**
